package com.yonyou.up.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-14T14:23:17.554+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "BPO_SUNTESTServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BPOSUNTESTServiceSoap {

    @WebResult(name = "getXML1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getXML1", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetXML1")
    @WebMethod(action = "http://tempuri.org/getXML1")
    @ResponseWrapper(localName = "getXML1Response", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetXML1Response")
    public java.lang.String getXML1(
        @WebParam(name = "per_UserID", targetNamespace = "http://tempuri.org/")
        java.lang.String perUserID,
        @WebParam(name = "per_BusiName", targetNamespace = "http://tempuri.org/")
        java.lang.String perBusiName,
        @WebParam(name = "per_configxml", targetNamespace = "http://tempuri.org/")
        java.lang.String perConfigxml
    );

    @WebResult(name = "GetUCMLBusinessDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUCMLBusinessData", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetUCMLBusinessData")
    @WebMethod(operationName = "GetUCMLBusinessData", action = "http://tempuri.org/GetUCMLBusinessData")
    @ResponseWrapper(localName = "GetUCMLBusinessDataResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetUCMLBusinessDataResponse")
    public com.yonyou.up.webservice.client.GetUCMLBusinessDataResponse.GetUCMLBusinessDataResult getUCMLBusinessData(
        @WebParam(name = "urlParams", targetNamespace = "http://tempuri.org/")
        java.lang.String urlParams,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "passWord", targetNamespace = "http://tempuri.org/")
        java.lang.String passWord
    );

    @WebResult(name = "getCondiBusinessAllData_NewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCondiBusinessAllData_New", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessAllDataNew")
    @WebMethod(operationName = "getCondiBusinessAllData_New", action = "http://tempuri.org/getCondiBusinessAllData_New")
    @ResponseWrapper(localName = "getCondiBusinessAllData_NewResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessAllDataNewResponse")
    public java.lang.String getCondiBusinessAllDataNew(
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix
    );

    @WebResult(name = "getCondiBusinessDataStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCondiBusinessDataString", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessDataString")
    @WebMethod(action = "http://tempuri.org/getCondiBusinessDataString")
    @ResponseWrapper(localName = "getCondiBusinessDataStringResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessDataStringResponse")
    public java.lang.String getCondiBusinessDataString(
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix
    );

    @WebResult(name = "InitBusinessEnvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InitBusinessEnv", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.InitBusinessEnv")
    @WebMethod(operationName = "InitBusinessEnv", action = "http://tempuri.org/InitBusinessEnv")
    @ResponseWrapper(localName = "InitBusinessEnvResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.InitBusinessEnvResponse")
    public com.yonyou.up.webservice.client.InitBusinessEnvResponse.InitBusinessEnvResult initBusinessEnv();

    @WebResult(name = "loadChildDataExStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loadChildDataExString", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoadChildDataExString")
    @WebMethod(action = "http://tempuri.org/loadChildDataExString")
    @ResponseWrapper(localName = "loadChildDataExStringResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoadChildDataExStringResponse")
    public java.lang.String loadChildDataExString(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "OID", targetNamespace = "http://tempuri.org/")
        java.lang.String oid,
        @WebParam(name = "recordXml", targetNamespace = "http://tempuri.org/")
        java.lang.String recordXml,
        @WebParam(name = "SubBC_SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String subBCSQLCondi
    );

    @RequestWrapper(localName = "SaveFlowChart", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.SaveFlowChart")
    @WebMethod(operationName = "SaveFlowChart", action = "http://tempuri.org/SaveFlowChart")
    @ResponseWrapper(localName = "SaveFlowChartResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.SaveFlowChartResponse")
    public void saveFlowChart(
        @WebParam(name = "Key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "FlowData", targetNamespace = "http://tempuri.org/")
        java.lang.String flowData
    );

    @WebResult(name = "CondiInitBusinessEnvExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CondiInitBusinessEnvEx", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CondiInitBusinessEnvEx")
    @WebMethod(operationName = "CondiInitBusinessEnvEx", action = "http://tempuri.org/CondiInitBusinessEnvEx")
    @ResponseWrapper(localName = "CondiInitBusinessEnvExResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CondiInitBusinessEnvExResponse")
    public com.yonyou.up.webservice.client.CondiInitBusinessEnvExResponse.CondiInitBusinessEnvExResult condiInitBusinessEnvEx(
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "sqlCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi
    );

    @WebResult(name = "getCondiBusinessDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCondiBusinessData", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessData")
    @WebMethod(action = "http://tempuri.org/getCondiBusinessData")
    @ResponseWrapper(localName = "getCondiBusinessDataResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessDataResponse")
    public com.yonyou.up.webservice.client.GetCondiBusinessDataResponse.GetCondiBusinessDataResult getCondiBusinessData(
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix
    );

    @WebResult(name = "GetDetailBusinessURLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDetailBusinessURL", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetDetailBusinessURL")
    @WebMethod(operationName = "GetDetailBusinessURL", action = "http://tempuri.org/GetDetailBusinessURL")
    @ResponseWrapper(localName = "GetDetailBusinessURLResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetDetailBusinessURLResponse")
    public java.lang.String getDetailBusinessURL(
        @WebParam(name = "auth", targetNamespace = "http://tempuri.org/")
        com.yonyou.up.webservice.client.Auth auth,
        @WebParam(name = "KpiID", targetNamespace = "http://tempuri.org/")
        java.lang.String kpiID,
        @WebParam(name = "Owner", targetNamespace = "http://tempuri.org/")
        java.lang.String owner,
        @WebParam(name = "OwnerType", targetNamespace = "http://tempuri.org/")
        int ownerType,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        java.lang.String endDate
    );

    @WebResult(name = "CondiInitBusinessEnvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CondiInitBusinessEnv", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CondiInitBusinessEnv")
    @WebMethod(operationName = "CondiInitBusinessEnv", action = "http://tempuri.org/CondiInitBusinessEnv")
    @ResponseWrapper(localName = "CondiInitBusinessEnvResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CondiInitBusinessEnvResponse")
    public com.yonyou.up.webservice.client.CondiInitBusinessEnvResponse.CondiInitBusinessEnvResult condiInitBusinessEnv(
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList
    );

    @RequestWrapper(localName = "AssignTaskForSign", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.AssignTaskForSign")
    @WebMethod(operationName = "AssignTaskForSign", action = "http://tempuri.org/AssignTaskForSign")
    @ResponseWrapper(localName = "AssignTaskForSignResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.AssignTaskForSignResponse")
    public void assignTaskForSign(
        @WebParam(name = "AssignTaskID", targetNamespace = "http://tempuri.org/")
        java.lang.String assignTaskID,
        @WebParam(name = "MasualAssign", targetNamespace = "http://tempuri.org/")
        java.lang.String masualAssign
    );

    @RequestWrapper(localName = "TaskReturn", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.TaskReturn")
    @WebMethod(operationName = "TaskReturn", action = "http://tempuri.org/TaskReturn")
    @ResponseWrapper(localName = "TaskReturnResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.TaskReturnResponse")
    public void taskReturn();

    @RequestWrapper(localName = "UpateVCPos", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.UpateVCPos")
    @WebMethod(operationName = "UpateVCPos", action = "http://tempuri.org/UpateVCPos")
    @ResponseWrapper(localName = "UpateVCPosResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.UpateVCPosResponse")
    public void upateVCPos(
        @WebParam(name = "strPane", targetNamespace = "http://tempuri.org/")
        java.lang.String strPane,
        @WebParam(name = "n32PaneSR", targetNamespace = "http://tempuri.org/")
        int n32PaneSR,
        @WebParam(name = "strPrmVCName", targetNamespace = "http://tempuri.org/")
        java.lang.String strPrmVCName,
        @WebParam(name = "PageID", targetNamespace = "http://tempuri.org/")
        java.lang.String pageID,
        @WebParam(name = "TypeID", targetNamespace = "http://tempuri.org/")
        java.lang.String typeID
    );

    @WebResult(name = "CondiInitBusinessEnvExStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CondiInitBusinessEnvExString", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CondiInitBusinessEnvExString")
    @WebMethod(operationName = "CondiInitBusinessEnvExString", action = "http://tempuri.org/CondiInitBusinessEnvExString")
    @ResponseWrapper(localName = "CondiInitBusinessEnvExStringResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CondiInitBusinessEnvExStringResponse")
    public java.lang.String condiInitBusinessEnvExString(
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "sqlCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi
    );

    @WebResult(name = "GetIndicatorValueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIndicatorValue", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetIndicatorValue")
    @WebMethod(operationName = "GetIndicatorValue", action = "http://tempuri.org/GetIndicatorValue")
    @ResponseWrapper(localName = "GetIndicatorValueResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetIndicatorValueResponse")
    public com.yonyou.up.webservice.client.ArrayOfDouble getIndicatorValue(
        @WebParam(name = "auth", targetNamespace = "http://tempuri.org/")
        com.yonyou.up.webservice.client.Auth auth,
        @WebParam(name = "KpiID", targetNamespace = "http://tempuri.org/")
        java.lang.String kpiID,
        @WebParam(name = "Owner", targetNamespace = "http://tempuri.org/")
        java.lang.String owner,
        @WebParam(name = "OwnerType", targetNamespace = "http://tempuri.org/")
        int ownerType,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        java.lang.String endDate
    );

    @WebResult(name = "buildTreeSubNodesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "buildTreeSubNodes", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BuildTreeSubNodes")
    @WebMethod(action = "http://tempuri.org/buildTreeSubNodes")
    @ResponseWrapper(localName = "buildTreeSubNodesResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BuildTreeSubNodesResponse")
    public java.lang.String buildTreeSubNodes(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "parentFieldName", targetNamespace = "http://tempuri.org/")
        java.lang.String parentFieldName,
        @WebParam(name = "parentOID", targetNamespace = "http://tempuri.org/")
        java.lang.String parentOID,
        @WebParam(name = "CaptionField", targetNamespace = "http://tempuri.org/")
        java.lang.String captionField
    );

    @RequestWrapper(localName = "SaveReportDefine", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.SaveReportDefine")
    @WebMethod(operationName = "SaveReportDefine", action = "http://tempuri.org/SaveReportDefine")
    @ResponseWrapper(localName = "SaveReportDefineResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.SaveReportDefineResponse")
    public void saveReportDefine(
        @WebParam(name = "ReportNo", targetNamespace = "http://tempuri.org/")
        java.lang.String reportNo,
        @WebParam(name = "ReportData", targetNamespace = "http://tempuri.org/")
        java.lang.String reportData
    );

    @WebResult(name = "GetSrvReportResultResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSrvReportResult", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetSrvReportResult")
    @WebMethod(operationName = "GetSrvReportResult", action = "http://tempuri.org/GetSrvReportResult")
    @ResponseWrapper(localName = "GetSrvReportResultResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetSrvReportResultResponse")
    public java.lang.String getSrvReportResult(
        @WebParam(name = "ReportID", targetNamespace = "http://tempuri.org/")
        java.lang.String reportID,
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "ReportParam", targetNamespace = "http://tempuri.org/")
        java.lang.String reportParam
    );

    @WebResult(name = "getCondiBusinessAllDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCondiBusinessAllData", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessAllData")
    @WebMethod(action = "http://tempuri.org/getCondiBusinessAllData")
    @ResponseWrapper(localName = "getCondiBusinessAllDataResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessAllDataResponse")
    public com.yonyou.up.webservice.client.GetCondiBusinessAllDataResponse.GetCondiBusinessAllDataResult getCondiBusinessAllData(
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix
    );

    @RequestWrapper(localName = "SetPageCount", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.SetPageCount")
    @WebMethod(operationName = "SetPageCount", action = "http://tempuri.org/SetPageCount")
    @ResponseWrapper(localName = "SetPageCountResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.SetPageCountResponse")
    public void setPageCount(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "pageCount", targetNamespace = "http://tempuri.org/")
        int pageCount
    );

    @WebResult(name = "getDynTreeSubNodesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getDynTreeSubNodes", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetDynTreeSubNodes")
    @WebMethod(action = "http://tempuri.org/getDynTreeSubNodes")
    @ResponseWrapper(localName = "getDynTreeSubNodesResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetDynTreeSubNodesResponse")
    public java.lang.String getDynTreeSubNodes(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "parentFieldName", targetNamespace = "http://tempuri.org/")
        java.lang.String parentFieldName,
        @WebParam(name = "parentOID", targetNamespace = "http://tempuri.org/")
        java.lang.String parentOID,
        @WebParam(name = "CaptionField", targetNamespace = "http://tempuri.org/")
        java.lang.String captionField
    );

    @RequestWrapper(localName = "AssignTaskForRead", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.AssignTaskForRead")
    @WebMethod(operationName = "AssignTaskForRead", action = "http://tempuri.org/AssignTaskForRead")
    @ResponseWrapper(localName = "AssignTaskForReadResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.AssignTaskForReadResponse")
    public void assignTaskForRead(
        @WebParam(name = "AssignTaskID", targetNamespace = "http://tempuri.org/")
        java.lang.String assignTaskID,
        @WebParam(name = "MasualAssign", targetNamespace = "http://tempuri.org/")
        java.lang.String masualAssign
    );

    @WebResult(name = "FinishTaskExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FinishTaskEx", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.FinishTaskEx")
    @WebMethod(operationName = "FinishTaskEx", action = "http://tempuri.org/FinishTaskEx")
    @ResponseWrapper(localName = "FinishTaskExResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.FinishTaskExResponse")
    public java.lang.String finishTaskEx(
        @WebParam(name = "FlowID", targetNamespace = "http://tempuri.org/")
        java.lang.String flowID,
        @WebParam(name = "AssignTaskID", targetNamespace = "http://tempuri.org/")
        java.lang.String assignTaskID
    );

    @RequestWrapper(localName = "DeleteQueryCondi", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.DeleteQueryCondi")
    @WebMethod(operationName = "DeleteQueryCondi", action = "http://tempuri.org/DeleteQueryCondi")
    @ResponseWrapper(localName = "DeleteQueryCondiResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.DeleteQueryCondiResponse")
    public void deleteQueryCondi(
        @WebParam(name = "OID", targetNamespace = "http://tempuri.org/")
        java.lang.String oid
    );

    @WebResult(name = "loadChildDataExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loadChildDataEx", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoadChildDataEx")
    @WebMethod(action = "http://tempuri.org/loadChildDataEx")
    @ResponseWrapper(localName = "loadChildDataExResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoadChildDataExResponse")
    public com.yonyou.up.webservice.client.LoadChildDataExResponse.LoadChildDataExResult loadChildDataEx(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "OID", targetNamespace = "http://tempuri.org/")
        java.lang.String oid,
        @WebParam(name = "recordXml", targetNamespace = "http://tempuri.org/")
        java.lang.String recordXml,
        @WebParam(name = "SubBC_SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String subBCSQLCondi
    );

    @WebResult(name = "putTOExcelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "putTOExcel", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.PutTOExcel")
    @WebMethod(action = "http://tempuri.org/putTOExcel")
    @ResponseWrapper(localName = "putTOExcelResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.PutTOExcelResponse")
    public java.lang.String putTOExcel(
        @WebParam(name = "nBCName", targetNamespace = "http://tempuri.org/")
        java.lang.String nBCName,
        @WebParam(name = "FieldLists", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldLists,
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix,
        @WebParam(name = "LocalResourcePath", targetNamespace = "http://tempuri.org/")
        java.lang.String localResourcePath
    );

    @RequestWrapper(localName = "AssignTaskToMe", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.AssignTaskToMe")
    @WebMethod(operationName = "AssignTaskToMe", action = "http://tempuri.org/AssignTaskToMe")
    @ResponseWrapper(localName = "AssignTaskToMeResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.AssignTaskToMeResponse")
    public void assignTaskToMe(
        @WebParam(name = "TaskOIDs", targetNamespace = "http://tempuri.org/")
        java.lang.String taskOIDs
    );

    @WebResult(name = "GetOrgNoOrDivisionNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOrgNoOrDivisionNo", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetOrgNoOrDivisionNo")
    @WebMethod(operationName = "GetOrgNoOrDivisionNo", action = "http://tempuri.org/GetOrgNoOrDivisionNo")
    @ResponseWrapper(localName = "GetOrgNoOrDivisionNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetOrgNoOrDivisionNoResponse")
    public java.lang.String getOrgNoOrDivisionNo(
        @WebParam(name = "infotype", targetNamespace = "http://tempuri.org/")
        int infotype
    );

    @WebResult(name = "CreateFlowResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateFlow", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CreateFlow")
    @WebMethod(operationName = "CreateFlow", action = "http://tempuri.org/CreateFlow")
    @ResponseWrapper(localName = "CreateFlowResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CreateFlowResponse")
    public java.lang.String createFlow(
        @WebParam(name = "FlowID", targetNamespace = "http://tempuri.org/")
        java.lang.String flowID
    );

    @WebResult(name = "PutToExcelEXResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PutToExcelEX", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.PutToExcelEX")
    @WebMethod(operationName = "PutToExcelEX", action = "http://tempuri.org/PutToExcelEX")
    @ResponseWrapper(localName = "PutToExcelEXResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.PutToExcelEXResponse")
    public java.lang.String putToExcelEX(
        @WebParam(name = "nBCName", targetNamespace = "http://tempuri.org/")
        java.lang.String nBCName,
        @WebParam(name = "FieldLists", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldLists,
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix,
        @WebParam(name = "LocalResourcePath", targetNamespace = "http://tempuri.org/")
        java.lang.String localResourcePath,
        @WebParam(name = "GridVCName", targetNamespace = "http://tempuri.org/")
        java.lang.String gridVCName,
        @WebParam(name = "MergerFieldIndex", targetNamespace = "http://tempuri.org/")
        java.lang.String mergerFieldIndex,
        @WebParam(name = "TitleTextLists", targetNamespace = "http://tempuri.org/")
        java.lang.String titleTextLists
    );

    @WebResult(name = "buildTreeGridSubDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "buildTreeGridSubData", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BuildTreeGridSubData")
    @WebMethod(action = "http://tempuri.org/buildTreeGridSubData")
    @ResponseWrapper(localName = "buildTreeGridSubDataResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BuildTreeGridSubDataResponse")
    public java.lang.String buildTreeGridSubData(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "parentFieldName", targetNamespace = "http://tempuri.org/")
        java.lang.String parentFieldName,
        @WebParam(name = "parentOID", targetNamespace = "http://tempuri.org/")
        java.lang.String parentOID,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords
    );

    @WebResult(name = "getCondiActorDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCondiActorData", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiActorData")
    @WebMethod(action = "http://tempuri.org/getCondiActorData")
    @ResponseWrapper(localName = "getCondiActorDataResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiActorDataResponse")
    public com.yonyou.up.webservice.client.GetCondiActorDataResponse.GetCondiActorDataResult getCondiActorData(
        @WebParam(name = "TableName", targetNamespace = "http://tempuri.org/")
        java.lang.String tableName,
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix
    );

    @WebResult(name = "ChangeBusiViewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangeBusiView", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.ChangeBusiView")
    @WebMethod(operationName = "ChangeBusiView", action = "http://tempuri.org/ChangeBusiView")
    @ResponseWrapper(localName = "ChangeBusiViewResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.ChangeBusiViewResponse")
    public com.yonyou.up.webservice.client.ChangeBusiViewResponse.ChangeBusiViewResult changeBusiView(
        @WebParam(name = "viewIndex", targetNamespace = "http://tempuri.org/")
        int viewIndex
    );

    @WebResult(name = "RollbackTaskResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RollbackTask", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.RollbackTask")
    @WebMethod(operationName = "RollbackTask", action = "http://tempuri.org/RollbackTask")
    @ResponseWrapper(localName = "RollbackTaskResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.RollbackTaskResponse")
    public java.lang.String rollbackTask(
        @WebParam(name = "FlowID", targetNamespace = "http://tempuri.org/")
        java.lang.String flowID,
        @WebParam(name = "TaskID", targetNamespace = "http://tempuri.org/")
        java.lang.String taskID
    );

    @WebResult(name = "getCondiActorDataBCStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCondiActorDataBCString", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiActorDataBCString")
    @WebMethod(action = "http://tempuri.org/getCondiActorDataBCString")
    @ResponseWrapper(localName = "getCondiActorDataBCStringResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiActorDataBCStringResponse")
    public java.lang.String getCondiActorDataBCString(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix
    );

    @WebResult(name = "LoginMobileResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoginMobile", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoginMobile")
    @WebMethod(operationName = "LoginMobile", action = "http://tempuri.org/LoginMobile")
    @ResponseWrapper(localName = "LoginMobileResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoginMobileResponse")
    public java.lang.String loginMobile(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebResult(name = "GetUCMLReportFileResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUCMLReportFile", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetUCMLReportFile")
    @WebMethod(operationName = "GetUCMLReportFile", action = "http://tempuri.org/GetUCMLReportFile")
    @ResponseWrapper(localName = "GetUCMLReportFileResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetUCMLReportFileResponse")
    public java.lang.String getUCMLReportFile(
        @WebParam(name = "urlParams", targetNamespace = "http://tempuri.org/")
        java.lang.String urlParams,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "passWord", targetNamespace = "http://tempuri.org/")
        java.lang.String passWord,
        @WebParam(name = "ReportID", targetNamespace = "http://tempuri.org/")
        java.lang.String reportID,
        @WebParam(name = "ExportType", targetNamespace = "http://tempuri.org/")
        int exportType
    );

    @WebResult(name = "ChangeBusiViewStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ChangeBusiViewString", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.ChangeBusiViewString")
    @WebMethod(operationName = "ChangeBusiViewString", action = "http://tempuri.org/ChangeBusiViewString")
    @ResponseWrapper(localName = "ChangeBusiViewStringResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.ChangeBusiViewStringResponse")
    public java.lang.String changeBusiViewString(
        @WebParam(name = "viewIndex", targetNamespace = "http://tempuri.org/")
        int viewIndex
    );

    @RequestWrapper(localName = "AssignTaskTo", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.AssignTaskTo")
    @WebMethod(operationName = "AssignTaskTo", action = "http://tempuri.org/AssignTaskTo")
    @ResponseWrapper(localName = "AssignTaskToResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.AssignTaskToResponse")
    public void assignTaskTo(
        @WebParam(name = "TaskOIDs", targetNamespace = "http://tempuri.org/")
        java.lang.String taskOIDs
    );

    @WebResult(name = "getTreeGridSubDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getTreeGridSubData", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetTreeGridSubData")
    @WebMethod(action = "http://tempuri.org/getTreeGridSubData")
    @ResponseWrapper(localName = "getTreeGridSubDataResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetTreeGridSubDataResponse")
    public java.lang.String getTreeGridSubData(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "parentFieldName", targetNamespace = "http://tempuri.org/")
        java.lang.String parentFieldName,
        @WebParam(name = "parentOID", targetNamespace = "http://tempuri.org/")
        java.lang.String parentOID,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords
    );

    @WebResult(name = "GetUniqueIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUniqueID", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetUniqueID")
    @WebMethod(operationName = "GetUniqueID", action = "http://tempuri.org/GetUniqueID")
    @ResponseWrapper(localName = "GetUniqueIDResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetUniqueIDResponse")
    public long getUniqueID(
        @WebParam(name = "KindStr", targetNamespace = "http://tempuri.org/")
        java.lang.String kindStr
    );

    @WebResult(name = "BusiViewStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BusiViewString", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BusiViewString")
    @WebMethod(operationName = "BusiViewString", action = "http://tempuri.org/BusiViewString")
    @ResponseWrapper(localName = "BusiViewStringResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BusiViewStringResponse")
    public java.lang.String busiViewString(
        @WebParam(name = "urlParams", targetNamespace = "http://tempuri.org/")
        java.lang.String urlParams
    );

    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.Login")
    @WebMethod(operationName = "Login", action = "http://tempuri.org/Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoginResponse")
    public int login(
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebResult(name = "GetSequenceNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSequenceNo", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetSequenceNo")
    @WebMethod(operationName = "GetSequenceNo", action = "http://tempuri.org/GetSequenceNo")
    @ResponseWrapper(localName = "GetSequenceNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetSequenceNoResponse")
    public long getSequenceNo(
        @WebParam(name = "KindStr", targetNamespace = "http://tempuri.org/")
        java.lang.String kindStr
    );

    @WebResult(name = "GetUserNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserName", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetUserName")
    @WebMethod(operationName = "GetUserName", action = "http://tempuri.org/GetUserName")
    @ResponseWrapper(localName = "GetUserNameResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetUserNameResponse")
    public java.lang.String getUserName();

    @WebResult(name = "CheckUniqueIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckUniqueID", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CheckUniqueID")
    @WebMethod(operationName = "CheckUniqueID", action = "http://tempuri.org/CheckUniqueID")
    @ResponseWrapper(localName = "CheckUniqueIDResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.CheckUniqueIDResponse")
    public long checkUniqueID(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "FieldName", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldName,
        @WebParam(name = "Value", targetNamespace = "http://tempuri.org/")
        java.lang.String value,
        @WebParam(name = "KeyValue", targetNamespace = "http://tempuri.org/")
        java.lang.String keyValue
    );

    @WebResult(name = "GetReportURLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReportURL", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetReportURL")
    @WebMethod(operationName = "GetReportURL", action = "http://tempuri.org/GetReportURL")
    @ResponseWrapper(localName = "GetReportURLResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetReportURLResponse")
    public java.lang.String getReportURL(
        @WebParam(name = "ReportID", targetNamespace = "http://tempuri.org/")
        java.lang.String reportID,
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "ReportParam", targetNamespace = "http://tempuri.org/")
        java.lang.String reportParam
    );

    @WebResult(name = "getTreeSubNodesWithChildResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getTreeSubNodesWithChild", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetTreeSubNodesWithChild")
    @WebMethod(action = "http://tempuri.org/getTreeSubNodesWithChild")
    @ResponseWrapper(localName = "getTreeSubNodesWithChildResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetTreeSubNodesWithChildResponse")
    public java.lang.String getTreeSubNodesWithChild(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "VCName", targetNamespace = "http://tempuri.org/")
        java.lang.String vcName,
        @WebParam(name = "parentFieldName", targetNamespace = "http://tempuri.org/")
        java.lang.String parentFieldName,
        @WebParam(name = "parentOID", targetNamespace = "http://tempuri.org/")
        java.lang.String parentOID,
        @WebParam(name = "CaptionField", targetNamespace = "http://tempuri.org/")
        java.lang.String captionField
    );

    @RequestWrapper(localName = "RightSystemInit", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.RightSystemInit")
    @WebMethod(operationName = "RightSystemInit", action = "http://tempuri.org/RightSystemInit")
    @ResponseWrapper(localName = "RightSystemInitResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.RightSystemInitResponse")
    public void rightSystemInit();

    @WebResult(name = "HavePermControlCodeRMResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HavePermControlCodeRM", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.HavePermControlCodeRM")
    @WebMethod(operationName = "HavePermControlCodeRM", action = "http://tempuri.org/HavePermControlCodeRM")
    @ResponseWrapper(localName = "HavePermControlCodeRMResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.HavePermControlCodeRMResponse")
    public boolean havePermControlCodeRM(
        @WebParam(name = "PersonOID", targetNamespace = "http://tempuri.org/")
        java.lang.String personOID,
        @WebParam(name = "BPOID", targetNamespace = "http://tempuri.org/")
        java.lang.String bpoid,
        @WebParam(name = "ControlCode", targetNamespace = "http://tempuri.org/")
        java.lang.String controlCode
    );

    @WebResult(name = "BusinessSubmitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BusinessSubmit", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BusinessSubmit")
    @WebMethod(operationName = "BusinessSubmit", action = "http://tempuri.org/BusinessSubmit")
    @ResponseWrapper(localName = "BusinessSubmitResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BusinessSubmitResponse")
    public java.lang.String businessSubmit(
        @WebParam(name = "xmlData", targetNamespace = "http://tempuri.org/")
        java.lang.String xmlData
    );

    @WebResult(name = "getCondiActorDataBCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCondiActorDataBC", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiActorDataBC")
    @WebMethod(action = "http://tempuri.org/getCondiActorDataBC")
    @ResponseWrapper(localName = "getCondiActorDataBCResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiActorDataBCResponse")
    public com.yonyou.up.webservice.client.GetCondiActorDataBCResponse.GetCondiActorDataBCResult getCondiActorDataBC(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix
    );

    @WebResult(name = "SaveQueryCondiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveQueryCondi", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.SaveQueryCondi")
    @WebMethod(operationName = "SaveQueryCondi", action = "http://tempuri.org/SaveQueryCondi")
    @ResponseWrapper(localName = "SaveQueryCondiResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.SaveQueryCondiResponse")
    public java.lang.String saveQueryCondi(
        @WebParam(name = "BPOName", targetNamespace = "http://tempuri.org/")
        java.lang.String bpoName,
        @WebParam(name = "VCName", targetNamespace = "http://tempuri.org/")
        java.lang.String vcName,
        @WebParam(name = "CondiName", targetNamespace = "http://tempuri.org/")
        java.lang.String condiName,
        @WebParam(name = "CondiValue", targetNamespace = "http://tempuri.org/")
        java.lang.String condiValue
    );

    @WebResult(name = "buildTreeSubNodesWithChildResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "buildTreeSubNodesWithChild", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BuildTreeSubNodesWithChild")
    @WebMethod(action = "http://tempuri.org/buildTreeSubNodesWithChild")
    @ResponseWrapper(localName = "buildTreeSubNodesWithChildResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.BuildTreeSubNodesWithChildResponse")
    public java.lang.String buildTreeSubNodesWithChild(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "VCName", targetNamespace = "http://tempuri.org/")
        java.lang.String vcName,
        @WebParam(name = "parentFieldName", targetNamespace = "http://tempuri.org/")
        java.lang.String parentFieldName,
        @WebParam(name = "parentOID", targetNamespace = "http://tempuri.org/")
        java.lang.String parentOID,
        @WebParam(name = "CaptionField", targetNamespace = "http://tempuri.org/")
        java.lang.String captionField
    );

    @WebResult(name = "LoadQueryCondiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoadQueryCondi", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoadQueryCondi")
    @WebMethod(operationName = "LoadQueryCondi", action = "http://tempuri.org/LoadQueryCondi")
    @ResponseWrapper(localName = "LoadQueryCondiResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoadQueryCondiResponse")
    public java.lang.String loadQueryCondi(
        @WebParam(name = "BPOName", targetNamespace = "http://tempuri.org/")
        java.lang.String bpoName,
        @WebParam(name = "VCName", targetNamespace = "http://tempuri.org/")
        java.lang.String vcName,
        @WebParam(name = "IsUser", targetNamespace = "http://tempuri.org/")
        boolean isUser
    );

    @WebResult(name = "getCondiBusinessDataExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getCondiBusinessDataEx", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessDataEx")
    @WebMethod(action = "http://tempuri.org/getCondiBusinessDataEx")
    @ResponseWrapper(localName = "getCondiBusinessDataExResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetCondiBusinessDataExResponse")
    public com.yonyou.up.webservice.client.GetCondiBusinessDataExResponse.GetCondiBusinessDataExResult getCondiBusinessDataEx(
        @WebParam(name = "nStartPos", targetNamespace = "http://tempuri.org/")
        long nStartPos,
        @WebParam(name = "nRecords", targetNamespace = "http://tempuri.org/")
        long nRecords,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix,
        @WebParam(name = "SubBC_SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String subBCSQLCondi
    );

    @WebResult(name = "loadChildDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loadChildData", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoadChildData")
    @WebMethod(action = "http://tempuri.org/loadChildData")
    @ResponseWrapper(localName = "loadChildDataResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.LoadChildDataResponse")
    public com.yonyou.up.webservice.client.LoadChildDataResponse.LoadChildDataResult loadChildData(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "OID", targetNamespace = "http://tempuri.org/")
        java.lang.String oid,
        @WebParam(name = "recordXml", targetNamespace = "http://tempuri.org/")
        java.lang.String recordXml
    );

    @WebResult(name = "FinishTaskResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FinishTask", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.FinishTask")
    @WebMethod(operationName = "FinishTask", action = "http://tempuri.org/FinishTask")
    @ResponseWrapper(localName = "FinishTaskResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.FinishTaskResponse")
    public java.lang.String finishTask(
        @WebParam(name = "AssignTaskID", targetNamespace = "http://tempuri.org/")
        java.lang.String assignTaskID
    );

    @WebResult(name = "getTotalDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getTotalData", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetTotalData")
    @WebMethod(action = "http://tempuri.org/getTotalData")
    @ResponseWrapper(localName = "getTotalDataResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetTotalDataResponse")
    public double getTotalData(
        @WebParam(name = "BCName", targetNamespace = "http://tempuri.org/")
        java.lang.String bcName,
        @WebParam(name = "fieldList", targetNamespace = "http://tempuri.org/")
        java.lang.String fieldList,
        @WebParam(name = "valueList", targetNamespace = "http://tempuri.org/")
        java.lang.String valueList,
        @WebParam(name = "condiIndentList", targetNamespace = "http://tempuri.org/")
        java.lang.String condiIndentList,
        @WebParam(name = "SQLCondi", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlCondi,
        @WebParam(name = "SQLCondiType", targetNamespace = "http://tempuri.org/")
        int sqlCondiType,
        @WebParam(name = "SQLFix", targetNamespace = "http://tempuri.org/")
        java.lang.String sqlFix,
        @WebParam(name = "TotalFields", targetNamespace = "http://tempuri.org/")
        java.lang.String totalFields,
        @WebParam(name = "TotalModes", targetNamespace = "http://tempuri.org/")
        java.lang.String totalModes
    );

    @WebResult(name = "GetbackTaskResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetbackTask", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetbackTask")
    @WebMethod(operationName = "GetbackTask", action = "http://tempuri.org/GetbackTask")
    @ResponseWrapper(localName = "GetbackTaskResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetbackTaskResponse")
    public java.lang.String getbackTask(
        @WebParam(name = "FlowID", targetNamespace = "http://tempuri.org/")
        java.lang.String flowID,
        @WebParam(name = "TaskID", targetNamespace = "http://tempuri.org/")
        java.lang.String taskID
    );

    @WebResult(name = "GetDateSequenceNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDateSequenceNo", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetDateSequenceNo")
    @WebMethod(operationName = "GetDateSequenceNo", action = "http://tempuri.org/GetDateSequenceNo")
    @ResponseWrapper(localName = "GetDateSequenceNoResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetDateSequenceNoResponse")
    public java.lang.String getDateSequenceNo(
        @WebParam(name = "KindStr", targetNamespace = "http://tempuri.org/")
        java.lang.String kindStr,
        @WebParam(name = "format", targetNamespace = "http://tempuri.org/")
        java.lang.String format,
        @WebParam(name = "sequenceCount", targetNamespace = "http://tempuri.org/")
        int sequenceCount
    );

    @WebResult(name = "HavePermBPORMResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HavePermBPORM", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.HavePermBPORM")
    @WebMethod(operationName = "HavePermBPORM", action = "http://tempuri.org/HavePermBPORM")
    @ResponseWrapper(localName = "HavePermBPORMResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.HavePermBPORMResponse")
    public boolean havePermBPORM(
        @WebParam(name = "PersonOID", targetNamespace = "http://tempuri.org/")
        java.lang.String personOID,
        @WebParam(name = "BPOID", targetNamespace = "http://tempuri.org/")
        java.lang.String bpoid
    );

    @WebResult(name = "GetSystemDateTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSystemDateTime", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetSystemDateTime")
    @WebMethod(operationName = "GetSystemDateTime", action = "http://tempuri.org/GetSystemDateTime")
    @ResponseWrapper(localName = "GetSystemDateTimeResponse", targetNamespace = "http://tempuri.org/", className = "cn.yonyou.up.webservice.client.GetSystemDateTimeResponse")
    public java.lang.String getSystemDateTime();
}
