package com.yonyou.up.webservice.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-14T14:23:17.632+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "BPO_SUNTESTService", 
                  wsdlLocation = "http://drptest.kukahome.com:88/KUKACustomer/BPO_SUNTEST.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class BPOSUNTESTService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "BPO_SUNTESTService");
    public final static QName BPOSUNTESTServiceSoap12 = new QName("http://tempuri.org/", "BPO_SUNTESTServiceSoap12");
    public final static QName BPOSUNTESTServiceSoap = new QName("http://tempuri.org/", "BPO_SUNTESTServiceSoap");
    static {
        URL url = BPOSUNTESTService.class.getResource("http://drptest.kukahome.com:88/KUKACustomer/BPO_SUNTEST.asmx?wsdl");
        if (url == null) {
            url = BPOSUNTESTService.class.getClassLoader().getResource("http://drptest.kukahome.com:88/KUKACustomer/BPO_SUNTEST.asmx?wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(BPOSUNTESTService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://drptest.kukahome.com:88/KUKACustomer/BPO_SUNTEST.asmx?wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public BPOSUNTESTService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BPOSUNTESTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BPOSUNTESTService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BPOSUNTESTService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BPOSUNTESTService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BPOSUNTESTService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns BPOSUNTESTServiceSoap
     */
    @WebEndpoint(name = "BPO_SUNTESTServiceSoap12")
    public BPOSUNTESTServiceSoap getBPOSUNTESTServiceSoap12() {
        return super.getPort(BPOSUNTESTServiceSoap12, BPOSUNTESTServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPOSUNTESTServiceSoap
     */
    @WebEndpoint(name = "BPO_SUNTESTServiceSoap12")
    public BPOSUNTESTServiceSoap getBPOSUNTESTServiceSoap12(WebServiceFeature... features) {
        return super.getPort(BPOSUNTESTServiceSoap12, BPOSUNTESTServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns BPOSUNTESTServiceSoap
     */
    @WebEndpoint(name = "BPO_SUNTESTServiceSoap")
    public BPOSUNTESTServiceSoap getBPOSUNTESTServiceSoap() {
        return super.getPort(BPOSUNTESTServiceSoap, BPOSUNTESTServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPOSUNTESTServiceSoap
     */
    @WebEndpoint(name = "BPO_SUNTESTServiceSoap")
    public BPOSUNTESTServiceSoap getBPOSUNTESTServiceSoap(WebServiceFeature... features) {
        return super.getPort(BPOSUNTESTServiceSoap, BPOSUNTESTServiceSoap.class, features);
    }

}
